
curl -XPUT 'http://localhost:9200/library/movies/1' -d '{"Title":"Godfather","Year":"1991","Rated":"N/A","Released":"N/A","Runtime":"150 min","Genre":"Comedy, Drama, Romance","Director":"Lal, Siddique","Writer":"Lal (screenplay), Siddique","Actors":"N.N. Pillai, Mukesh, Kanaka, Philomina","Plot":"Two youngsters from rival clans fall in love.","Language":"Malayalam","Country":"India","Awards":"2 wins.","Poster":"N/A","Metascore":"N/A","imdbRating":"8.3","imdbVotes":"606","imdbID":"tt0353496","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/2' -d '{"Title":"Pulp Fiction","Year":"1994","Rated":"R","Released":"14 Oct 1994","Runtime":"154 min","Genre":"Crime, Drama","Director":"Quentin Tarantino","Writer":"Quentin Tarantino (story), Roger Avary (story), Quentin Tarantino","Actors":"Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta","Plot":"The lives of two mob hit men, a boxer, a gangsters wife, and a pair of diner bandits intertwine in four tales of violence and redemption.","Language":"English, Spanish, French","Country":"USA","Awards":"Won 1 Oscar. Another 63 wins & 47 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjE0ODk2NjczOV5BMl5BanBnXkFtZTYwNDQ0NDg4._V1_SX300.jpg","Metascore":"94","imdbRating":"8.9","imdbVotes":"1132720","imdbID":"tt0110912","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/3' -d '{"Title":"Terminator","Year":"2001","Rated":"N/A","Released":"1 Apr 2001","Runtime":"N/A","Genre":"Short, Action","Director":"Ryan McDonald","Writer":"Ryan McDonald","Actors":"Joshua Miller","Plot":"N/A","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"3.8","imdbVotes":"12","imdbID":"tt1994570","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/4' -d '{"Title":"Fight Club","Year":"1999","Rated":"R","Released":"15 Oct 1999","Runtime":"139 min","Genre":"Drama","Director":"David Fincher","Writer":"Chuck Palahniuk (novel), Jim Uhls (screenplay)","Actors":"Edward Norton, Brad Pitt, Helena Bonham Carter, Meat Loaf","Plot":"An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more...","Language":"English","Country":"USA, Germany","Awards":"Nominated for 1 Oscar. Another 10 wins & 22 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjIwNTYzMzE1M15BMl5BanBnXkFtZTcwOTE5Mzg3OA@@._V1_SX300.jpg","Metascore":"66","imdbRating":"8.9","imdbVotes":"1141595","imdbID":"tt0137523","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/5' -d '{"Title":"The Lord of the Rings: The Fellowship of the Ring","Year":"2001","Rated":"PG-13","Released":"19 Dec 2001","Runtime":"178 min","Genre":"Adventure, Fantasy","Director":"Peter Jackson","Writer":"J.R.R. Tolkien (novel), Fran Walsh (screenplay), Philippa Boyens (screenplay), Peter Jackson (screenplay)","Actors":"Alan Howard, Noel Appleby, Sean Astin, Sala Baker","Plot":"A meek hobbit of the Shire and eight companions set out on a journey to Mount Doom to destroy the One Ring and the dark lord Sauron.","Language":"English, Sindarin","Country":"New Zealand, USA","Awards":"Won 4 Oscars. Another 109 wins & 100 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNTEyMjAwMDU1OV5BMl5BanBnXkFtZTcwNDQyNTkxMw@@._V1_SX300.jpg","Metascore":"92","imdbRating":"8.8","imdbVotes":"1070311","imdbID":"tt0120737","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/6' -d '{"Title":"The Godfather: Part II","Year":"1974","Rated":"R","Released":"20 Dec 1974","Runtime":"200 min","Genre":"Crime, Drama","Director":"Francis Ford Coppola","Writer":"Francis Ford Coppola (screenplay), Mario Puzo (screenplay), Mario Puzo (based on the novel \"The Godfather\" by)","Actors":"Al Pacino, Robert Duvall, Diane Keaton, Robert De Niro","Plot":"The early life and career of Vito Corleone in 1920s New York is portrayed while his son, Michael, expands and tightens his grip on his crime syndicate stretching from Lake Tahoe, Nevada to pre-revolution 1958 Cuba.","Language":"English, Italian, Spanish, Latin, Sicilian","Country":"USA","Awards":"Won 6 Oscars. Another 13 wins & 16 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDc2NTM3MzU1Nl5BMl5BanBnXkFtZTcwMTA5Mzg3OA@@._V1_SX300.jpg","Metascore":"80","imdbRating":"9.1","imdbVotes":"673844","imdbID":"tt0071562","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/7' -d '{"Title":"Inception","Year":"2010","Rated":"PG-13","Released":"16 Jul 2010","Runtime":"148 min","Genre":"Action, Mystery, Sci-Fi","Director":"Christopher Nolan","Writer":"Christopher Nolan","Actors":"Leonardo DiCaprio, Joseph Gordon-Levitt, Ellen Page, Tom Hardy","Plot":"A thief who steals corporate secrets through use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.","Language":"English, Japanese, French","Country":"USA, UK","Awards":"Won 4 Oscars. Another 153 wins & 171 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.8","imdbVotes":"1236546","imdbID":"tt1375666","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/8' -d '{"Title":"The Matrix","Year":"1999","Rated":"R","Released":"31 Mar 1999","Runtime":"136 min","Genre":"Action, Sci-Fi","Director":"Andy Wachowski, Lana Wachowski","Writer":"Andy Wachowski, Lana Wachowski","Actors":"Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving","Plot":"A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.","Language":"English","Country":"USA, Australia","Awards":"Won 4 Oscars. Another 34 wins & 40 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTkxNDYxOTA4M15BMl5BanBnXkFtZTgwNTk0NzQxMTE@._V1_SX300.jpg","Metascore":"73","imdbRating":"8.7","imdbVotes":"1037112","imdbID":"tt0133093","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/9' -d '{"Title":"Seven Samurai","Year":"1954","Rated":"UNRATED","Released":"19 Nov 1956","Runtime":"207 min","Genre":"Drama","Director":"Akira Kurosawa","Writer":"Akira Kurosawa (screenplay), Shinobu Hashimoto (screenplay), Hideo Oguni (screenplay)","Actors":"Toshirô Mifune, Takashi Shimura, Keiko Tsushima, Yukiko Shimazaki","Plot":"A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.","Language":"Japanese","Country":"Japan","Awards":"Nominated for 2 Oscars. Another 6 wins & 5 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTc5MDY1MjU5MF5BMl5BanBnXkFtZTgwNDM2OTE4MzE@._V1_SX300.jpg","Metascore":"99","imdbRating":"8.7","imdbVotes":"202210","imdbID":"tt0047478","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/10' -d '{"Title":"City of God","Year":"2002","Rated":"R","Released":"13 Feb 2004","Runtime":"130 min","Genre":"Crime, Drama","Director":"Fernando Meirelles, Kátia Lund","Writer":"Paulo Lins (novel), Bráulio Mantovani (screenplay)","Actors":"Alexandre Rodrigues, Leandro Firmino, Phellipe Haagensen, Douglas Silva","Plot":"Two boys growing up in a violent neighborhood of Rio de Janeiro take different paths: one becomes a photographer, the other a drug dealer.","Language":"Portuguese","Country":"Brazil, France","Awards":"Nominated for 4 Oscars. Another 70 wins & 29 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA4ODQ3ODkzNV5BMl5BanBnXkFtZTYwOTc4NDI3._V1_SX300.jpg","Metascore":"79","imdbRating":"8.7","imdbVotes":"465143","imdbID":"tt0317248","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/11' -d '{"Title":"Léon: The Professional","Year":"1994","Rated":"R","Released":"18 Nov 1994","Runtime":"110 min","Genre":"Crime, Drama, Thriller","Director":"Luc Besson","Writer":"Luc Besson","Actors":"Jean Reno, Gary Oldman, Natalie Portman, Danny Aiello","Plot":"Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. Léon and Mathilda form an unusual relationship, as she becomes his protégée and learns the assassins trade.","Language":"English, Italian, French","Country":"France","Awards":"3 wins & 8 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTgzMzg4MDkwNF5BMl5BanBnXkFtZTcwODAwNDg3OA@@._V1_SX300.jpg","Metascore":"64","imdbRating":"8.6","imdbVotes":"617410","imdbID":"tt0110413","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/12' -d '{"Title":"Interstellar","Year":"2014","Rated":"PG-13","Released":"7 Nov 2014","Runtime":"169 min","Genre":"Adventure, Sci-Fi","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan","Actors":"Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow","Plot":"A team of explorers travel through a wormhole in an attempt to ensure humanitys survival.","Language":"English","Country":"USA, UK, Canada","Awards":"Won 1 Oscar. Another 35 wins & 102 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.7","imdbVotes":"613509","imdbID":"tt0816692","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/13' -d '{"Title":"The Intouchables","Year":"2011","Rated":"R","Released":"2 Nov 2011","Runtime":"112 min","Genre":"Biography, Comedy, Drama","Director":"Olivier Nakache, Eric Toledano","Writer":"Olivier Nakache, Eric Toledano","Actors":"François Cluzet, Omar Sy, Anne Le Ny, Audrey Fleurot","Plot":"After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.","Language":"French, English","Country":"France","Awards":"Nominated for 1 Golden Globe. Another 31 wins & 36 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SX300.jpg","Metascore":"57","imdbRating":"8.6","imdbVotes":"399160","imdbID":"tt1675434","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/14' -d '{"Title":"Terminator 2: Judgment Day","Year":"1991","Rated":"R","Released":"3 Jul 1991","Runtime":"137 min","Genre":"Action, Sci-Fi","Director":"James Cameron","Writer":"James Cameron, William Wisher Jr.","Actors":"Arnold Schwarzenegger, Linda Hamilton, Edward Furlong, Robert Patrick","Plot":"A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her young son, John Connor, from a more advanced cyborg, made out of liquid metal.","Language":"English, Spanish","Country":"USA, France","Awards":"Won 4 Oscars. Another 20 wins & 21 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTg5NzUwMDU5NF5BMl5BanBnXkFtZTcwMjk2MDA4Mg@@._V1_SX300.jpg","Metascore":"68","imdbRating":"8.5","imdbVotes":"636472","imdbID":"tt0103064","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/15' -d '{"Title":"The Green Mile","Year":"1999","Rated":"R","Released":"10 Dec 1999","Runtime":"189 min","Genre":"Crime, Drama, Fantasy","Director":"Frank Darabont","Writer":"Stephen King (novel), Frank Darabont (screenplay)","Actors":"Tom Hanks, David Morse, Michael Clarke Duncan, Bonnie Hunt","Plot":"The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.","Language":"English, French","Country":"USA","Awards":"Nominated for 4 Oscars. Another 15 wins & 26 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg","Metascore":"61","imdbRating":"8.5","imdbVotes":"649833","imdbID":"tt0120689","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/16' -d '{"Title":"The Departed","Year":"2006","Rated":"R","Released":"6 Oct 2006","Runtime":"151 min","Genre":"Crime, Drama, Thriller","Director":"Martin Scorsese","Writer":"William Monahan (screenplay), Alan Mak, Felix Chong","Actors":"Leonardo DiCaprio, Matt Damon, Jack Nicholson, Mark Wahlberg","Plot":"An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.","Language":"English, Cantonese","Country":"USA, Hong Kong","Awards":"Won 4 Oscars. Another 93 wins & 83 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg","Metascore":"86","imdbRating":"8.5","imdbVotes":"741692","imdbID":"tt0407887","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/17' -d '{"Title":"Gladiator","Year":"2000","Rated":"R","Released":"5 May 2000","Runtime":"155 min","Genre":"Action, Drama","Director":"Ridley Scott","Writer":"David Franzoni (story), David Franzoni (screenplay), John Logan (screenplay), William Nicholson (screenplay)","Actors":"Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed","Plot":"When a Roman general is betrayed and his family murdered by an emperors corrupt son, he comes to Rome as a gladiator to seek revenge.","Language":"English","Country":"USA, UK","Awards":"Won 5 Oscars. Another 58 wins & 94 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTgwMzQzNTQ1Ml5BMl5BanBnXkFtZTgwMDY2NTYxMTE@._V1_SX300.jpg","Metascore":"64","imdbRating":"8.5","imdbVotes":"837051","imdbID":"tt0172495","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/18' -d '{"Title":"Back to the Future","Year":"1985","Rated":"PG","Released":"3 Jul 1985","Runtime":"116 min","Genre":"Adventure, Comedy, Romance","Director":"Robert Zemeckis","Writer":"Robert Zemeckis, Bob Gale","Actors":"Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover","Plot":"A young man is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his friend, Dr. Emmett Brown, and must make sure his high-school-age parents unite in order to save his own existence.","Language":"English","Country":"USA","Awards":"Won 1 Oscar. Another 18 wins & 24 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA5NTYzMDMyM15BMl5BanBnXkFtZTgwNjU3NDU2MTE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.5","imdbVotes":"608026","imdbID":"tt0088763","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/19' -d '{"Title":"Alien","Year":"1979","Rated":"R","Released":"22 Jun 1979","Runtime":"117 min","Genre":"Horror, Sci-Fi","Director":"Ridley Scott","Writer":"Dan OBannon (story), Ronald Shusett (story), Dan OBannon (screenplay)","Actors":"Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton","Plot":"The commercial vessel Nostromo receives a distress call from an unexplored planet. After searching for survivors, the crew heads home only to realize that a deadly bioform has joined them.","Language":"English, Spanish","Country":"USA, UK","Awards":"Won 1 Oscar. Another 15 wins & 18 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTU1ODQ4NjQyOV5BMl5BanBnXkFtZTgwOTQ3NDU2MTE@._V1_SX300.jpg","Metascore":"83","imdbRating":"8.5","imdbVotes":"482280","imdbID":"tt0078748","Type":"movie","Response":"True"}'



curl -XPUT 'http://localhost:9200/library/movies/20' -d{"Title":"The Great Dictator","Year":"1940","Rated":"APPROVED","Released":"7 Mar 1941","Runtime":"125 min","Genre":"Comedy, Drama, War","Director":"Charles Chaplin","Writer":"Charles Chaplin","Actors":"Charles Chaplin, Jack Oakie, Reginald Gardiner, Henry Daniell","Plot":"Dictator Adenoid Hynkel tries to expand his empire while a poor Jewish barber tries to avoid persecution from Hynkels regime.","Language":"English, Esperanto","Country":"USA","Awards":"Nominated for 5 Oscars. Another 5 wins & 1 nomination.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ5NDAwMDgzOV5BMl5BanBnXkFtZTgwNDI2MjA0MjE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.5","imdbVotes":"114503","imdbID":"tt0032553","Type":"movie","Response":"True"}

curl -XPUT 'http://localhost:9200/library/movies/21' -d '{"Title":"The Dictator","Year":"2012","Rated":"R","Released":"16 May 2012","Runtime":"83 min","Genre":"Comedy","Director":"Larry Charles","Writer":"Sacha Baron Cohen, Alec Berg, David Mandel, Jeff Schaffer","Actors":"Sacha Baron Cohen, Sayed Badreya, Rocky Citron, Liam Campora","Plot":"The heroic story of a dictator who risks his life to ensure that democracy would never come to the country he so lovingly oppressed.","Language":"English, Hebrew","Country":"USA","Awards":"1 win & 1 nomination.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjA4NjEyOTc4NV5BMl5BanBnXkFtZTcwODYzMjk2Nw@@._V1_SX300.jpg","Metascore":"58","imdbRating":"6.4","imdbVotes":"188699","imdbID":"tt1645170","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/22' -d '{"Title":"Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan","Year":"2006","Rated":"R","Released":"3 Nov 2006","Runtime":"84 min","Genre":"Comedy","Director":"Larry Charles","Writer":"Sacha Baron Cohen (screenplay), Anthony Hines (screenplay), Peter Baynham (screenplay), Dan Mazer (screenplay), Sacha Baron Cohen (story), Peter Baynham (story), Anthony Hines (story), Todd Phillips (story), Sacha Baron Cohen (based on a character created by)","Actors":"Sacha Baron Cohen, Ken Davitian, Luenell, Chester","Plot":"Kazakh TV talking head Borat is dispatched to the United States to report on the greatest country in the world. With a documentary crew in tow, Borat becomes more interested in locating and marrying Pamela Anderson.","Language":"English, Romanian, Hebrew, Polish, Armenian","Country":"USA, UK","Awards":"Nominated for 1 Oscar. Another 21 wins & 17 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk0MTQ3NDQ4Ml5BMl5BanBnXkFtZTcwOTQ3OTQzMw@@._V1_SX300.jpg","Metascore":"89","imdbRating":"7.3","imdbVotes":"270157","imdbID":"tt0443453","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/23' -d '{"Title":"Django Unchained","Year":"2012","Rated":"R","Released":"25 Dec 2012","Runtime":"165 min","Genre":"Western","Director":"Quentin Tarantino","Writer":"Quentin Tarantino","Actors":"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio, Kerry Washington","Plot":"With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.","Language":"English, German, French","Country":"USA","Awards":"Won 2 Oscars. Another 65 wins & 105 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1_SX300.jpg","Metascore":"81","imdbRating":"8.5","imdbVotes":"777356","imdbID":"tt1853728","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/24' -d '{"Title":"The Dark Knight Rises","Year":"2012","Rated":"PG-13","Released":"20 Jul 2012","Runtime":"165 min","Genre":"Action, Thriller","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)","Actors":"Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt","Plot":"Eight years after the Jokers reign of anarchy, the Dark Knight is forced to return from his imposed exile to save Gotham City from the brutal guerrilla terrorist Bane with the help of the enigmatic Catwoman.","Language":"English","Country":"USA, UK","Awards":"Nominated for 1 BAFTA Film Award. Another 43 wins & 82 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg","Metascore":"78","imdbRating":"8.5","imdbVotes":"960800","imdbID":"tt1345836","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/25' -d '{"Title":"The Dark Knight Rises","Year":"2012","Rated":"PG-13","Released":"20 Jul 2012","Runtime":"165 min","Genre":"Action, Thriller","Director":"Christopher Nolan","Writer":"Jonathan Nolan (screenplay), Christopher Nolan (screenplay), Christopher Nolan (story), David S. Goyer (story), Bob Kane (characters)","Actors":"Christian Bale, Gary Oldman, Tom Hardy, Joseph Gordon-Levitt","Plot":"Eight years after the Jokers reign of anarchy, the Dark Knight is forced to return from his imposed exile to save Gotham City from the brutal guerrilla terrorist Bane with the help of the enigmatic Catwoman.","Language":"English","Country":"USA, UK","Awards":"Nominated for 1 BAFTA Film Award. Another 43 wins & 82 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_SX300.jpg","Metascore":"78","imdbRating":"8.5","imdbVotes":"960800","imdbID":"tt1345836","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/26' -d '{"Title":"Reservoir Dogs","Year":"1992","Rated":"R","Released":"2 Sep 1992","Runtime":"99 min","Genre":"Crime, Drama","Director":"Quentin Tarantino","Writer":"Quentin Tarantino, Roger Avary (background radio dialog), Quentin Tarantino (background radio dialog)","Actors":"Harvey Keitel, Tim Roth, Michael Madsen, Chris Penn","Plot":"After a simple jewelery heist goes terribly wrong, the surviving criminals begin to suspect that one of them is a police informant.","Language":"English","Country":"USA","Awards":"12 wins & 10 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQxMTAwMDQ3Nl5BMl5BanBnXkFtZTcwODMwNTgzMQ@@._V1_SX300.jpg","Metascore":"78","imdbRating":"8.4","imdbVotes":"563327","imdbID":"tt0105236","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/27' -d '{"Title":"Inglourious Basterds","Year":"2009","Rated":"R","Released":"21 Aug 2009","Runtime":"153 min","Genre":"Adventure, Drama, War","Director":"Quentin Tarantino, Eli Roth","Writer":"Quentin Tarantino","Actors":"Brad Pitt, Mélanie Laurent, Christoph Waltz, Eli Roth","Plot":"In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owners vengeful plans for the same.","Language":"English, German, French, Italian","Country":"USA, Germany","Awards":"Won 1 Oscar. Another 137 wins & 111 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjIzMDI4MTUzOV5BMl5BanBnXkFtZTcwNDY3NjA3Mg@@._V1_SX300.jpg","Metascore":"69","imdbRating":"8.3","imdbVotes":"734067","imdbID":"tt0361748","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/28' -d '{"Title":"Pirates of the Caribbean: The Curse of the Black Pearl","Year":"2003","Rated":"PG-13","Released":"9 Jul 2003","Runtime":"143 min","Genre":"Adventure, Fantasy","Director":"Gore Verbinski","Writer":"Ted Elliott (screen story), Terry Rossio (screen story), Stuart Beattie (screen story), Jay Wolpert (screen story), Ted Elliott (screenplay), Terry Rossio (screenplay)","Actors":"Johnny Depp, Geoffrey Rush, Orlando Bloom, Keira Knightley","Plot":"Blacksmith Will Turner teams up with eccentric pirate \"Captain\" Jack Sparrow to save his love, the governors daughter, from Jacks former pirate allies, who are now undead.","Language":"English","Country":"USA","Awards":"Nominated for 5 Oscars. Another 31 wins & 77 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAyNDM4MTc2N15BMl5BanBnXkFtZTYwNDk0Mjc3._V1_SX300.jpg","Metascore":"63","imdbRating":"8.1","imdbVotes":"698237","imdbID":"tt0325980","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/29' -d '{"Title":"Batman Begins","Year":"2005","Rated":"PG-13","Released":"15 Jun 2005","Runtime":"140 min","Genre":"Action, Adventure","Director":"Christopher Nolan","Writer":"Bob Kane (characters), David S. Goyer (story), Christopher Nolan (screenplay), David S. Goyer (screenplay)","Actors":"Christian Bale, Michael Caine, Liam Neeson, Katie Holmes","Plot":"After training with his mentor, Batman begins his war on crime to free the crime-ridden Gotham City from corruption that the Scarecrow and the League of Shadows have cast upon it.","Language":"English, Urdu, Mandarin","Country":"USA, UK","Awards":"Nominated for 1 Oscar. Another 17 wins & 48 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNTM3OTc0MzM2OV5BMl5BanBnXkFtZTYwNzUwMTI3._V1_SX300.jpg","Metascore":"70","imdbRating":"8.3","imdbVotes":"822679","imdbID":"tt0372784","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/30' -d '{"Title":"Scarface","Year":"1983","Rated":"R","Released":"9 Dec 1983","Runtime":"170 min","Genre":"Crime, Drama","Director":"Brian De Palma","Writer":"Oliver Stone (screenplay)","Actors":"Al Pacino, Steven Bauer, Michelle Pfeiffer, Mary Elizabeth Mastrantonio","Plot":"In 1980 Miami, a determined Cuban immigrant takes over a drug cartel while succumbing to greed.","Language":"English, Spanish","Country":"USA","Awards":"Nominated for 3 Golden Globes. Another 3 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjAzOTM4MzEwNl5BMl5BanBnXkFtZTgwMzU1OTc1MDE@._V1_SX300.jpg","Metascore":"65","imdbRating":"8.3","imdbVotes":"463340","imdbID":"tt0086250","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/31' -d '{"Title":"Up","Year":"2009","Rated":"PG","Released":"29 May 2009","Runtime":"96 min","Genre":"Animation, Adventure, Comedy","Director":"Pete Docter, Bob Peterson","Writer":"Pete Docter (story), Bob Peterson (story), Thomas McCarthy (story), Bob Peterson (screenplay), Pete Docter (screenplay)","Actors":"Edward Asner, Christopher Plummer, Jordan Nagai, Bob Peterson","Plot":"To avoid being taken away to a nursing home, an old widower tries to fly his home to Paradise Falls, South America, along with a boy scout who accidentally lifted off with him.","Language":"English","Country":"USA","Awards":"Won 2 Oscars. Another 77 wins & 56 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk3NDE2NzI4NF5BMl5BanBnXkFtZTgwNzE1MzEyMTE@._V1_SX300.jpg","Metascore":"88","imdbRating":"8.3","imdbVotes":"543525","imdbID":"tt1049413","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/32' -d '{"Title":"Chinatown","Year":"1974","Rated":"R","Released":"20 Jun 1974","Runtime":"130 min","Genre":"Drama, Mystery, Thriller","Director":"Roman Polanski","Writer":"Robert Towne","Actors":"Jack Nicholson, Faye Dunaway, John Huston, Perry Lopez","Plot":"A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption and murder.","Language":"English, Cantonese, Spanish","Country":"USA","Awards":"Won 1 Oscar. Another 21 wins & 22 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTUyMTQ1NjA2OV5BMl5BanBnXkFtZTcwODQ1Njg3OA@@._V1_SX300.jpg","Metascore":"86","imdbRating":"8.3","imdbVotes":"188467","imdbID":"tt0071315","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/33' -d '{"Title":"Die Hard","Year":"1988","Rated":"R","Released":"20 Jul 1988","Runtime":"131 min","Genre":"Action, Thriller","Director":"John McTiernan","Writer":"Roderick Thorp (novel), Jeb Stuart (screenplay), Steven E. de Souza (screenplay)","Actors":"Bruce Willis, Bonnie Bedelia, Reginald VelJohnson, Paul Gleason","Plot":"John McClane, officer of the NYPD, tries to save wife Holly Gennaro and several others, taken hostage by German terrorist Hans Gruber during a Christmas party at the Nakatomi Plaza in Los Angeles.","Language":"English, German, Italian","Country":"USA","Awards":"Nominated for 4 Oscars. Another 6 wins & 2 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY4ODM0OTc2M15BMl5BanBnXkFtZTcwNzE0MTk3OA@@._V1_SX300.jpg","Metascore":"70","imdbRating":"8.3","imdbVotes":"517218","imdbID":"tt0095016","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/34' -d '{"Title":"The One","Year":"2001","Rated":"PG-13","Released":"2 Nov 2001","Runtime":"87 min","Genre":"Action, Sci-Fi, Thriller","Director":"James Wong","Writer":"Glen Morgan, James Wong","Actors":"Jet Li, Carla Gugino, Delroy Lindo, Jason Statham","Plot":"A sheriffs deputy fights an alternate universe version of himself who grows stronger with each alternate self he kills.","Language":"English","Country":"USA","Awards":"4 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BNTgxNTkzOTU2NF5BMl5BanBnXkFtZTYwMjcwNjQ5._V1_SX300.jpg","Metascore":"25","imdbRating":"5.9","imdbVotes":"73008","imdbID":"tt0267804","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/35' -d '{"Title":"Casino","Year":"1995","Rated":"R","Released":"22 Nov 1995","Runtime":"178 min","Genre":"Biography, Crime, Drama","Director":"Martin Scorsese","Writer":"Nicholas Pileggi (book), Nicholas Pileggi (screenplay), Martin Scorsese (screenplay)","Actors":"Robert De Niro, Sharon Stone, Joe Pesci, James Woods","Plot":"Greed, deception, money, power, and murder occur between two mobster best friends and a trophy wife over a gambling empire.","Language":"English","Country":"USA, France","Awards":"Nominated for 1 Oscar. Another 4 wins & 7 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTMzMjkwMTk4Nl5BMl5BanBnXkFtZTYwNjYxMjk5._V1_SX300.jpg","Metascore":"73","imdbRating":"8.2","imdbVotes":"286947","imdbID":"tt0112641","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/36' -d '{"Title":"Warrior","Year":"2011","Rated":"PG-13","Released":"9 Sep 2011","Runtime":"140 min","Genre":"Drama, Sport","Director":"Gavin OConnor","Writer":"Gavin OConnor (screenplay), Anthony Tambakis (screenplay), Cliff Dorfman (screenplay), Gavin OConnor (story), Cliff Dorfman (story)","Actors":"Joel Edgerton, Tom Hardy, Nick Nolte, Jennifer Morrison","Plot":"The youngest son of an alcoholic former boxer returns home, where hes trained by his father for competition in a mixed martial arts tournament - a path that puts the fighter on a collision course with his estranged, older brother.","Language":"English, Spanish","Country":"USA","Awards":"Nominated for 1 Oscar. Another 4 wins & 15 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk4ODk5MTMyNV5BMl5BanBnXkFtZTcwMDMyNTg0Ng@@._V1_SX300.jpg","Metascore":"71","imdbRating":"8.2","imdbVotes":"278130","imdbID":"tt1291584","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/37' -d '{"Title":"Gran Torino","Year":"2008","Rated":"R","Released":"9 Jan 2009","Runtime":"116 min","Genre":"Drama","Director":"Clint Eastwood","Writer":"Nick Schenk (screenplay), Dave Johannson (story), Nick Schenk (story)","Actors":"Clint Eastwood, Christopher Carley, Bee Vang, Ahney Her","Plot":"Disgruntled Korean War veteran Walt Kowalski sets out to reform his neighbor, a Hmong teenager who tried to steal Kowalskis prized possession: a 1972 Gran Torino.","Language":"English, Hmong","Country":"USA, Germany","Awards":"Nominated for 1 Golden Globe. Another 22 wins & 10 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQyMTczMTAxMl5BMl5BanBnXkFtZTcwOTc1ODE0Mg@@._V1_SX300.jpg","Metascore":"72","imdbRating":"8.2","imdbVotes":"488277","imdbID":"tt1205489","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/38' -d '{"Title":"The Big Lebowski","Year":"1998","Rated":"R","Released":"6 Mar 1998","Runtime":"117 min","Genre":"Comedy, Crime","Director":"Joel Coen, Ethan Coen","Writer":"Ethan Coen, Joel Coen","Actors":"Jeff Bridges, John Goodman, Julianne Moore, Steve Buscemi","Plot":"\"The Dude\" Lebowski, mistaken for a millionaire Lebowski, seeks restitution for his ruined rug and enlists his bowling buddies to help get it.","Language":"English, German, Hebrew, Spanish","Country":"USA, UK","Awards":"4 wins & 14 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ0NjUzMDMyOF5BMl5BanBnXkFtZTgwODA1OTU0MDE@._V1_SX300.jpg","Metascore":"69","imdbRating":"8.2","imdbVotes":"458717","imdbID":"tt0118715","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/39' -d '{"Title":"V for Vendetta","Year":"2005","Rated":"R","Released":"17 Mar 2006","Runtime":"132 min","Genre":"Action, Drama, Thriller","Director":"James McTeigue","Writer":"Andy Wachowski (screenplay), Lana Wachowski (screenplay), David Lloyd (graphic novel art)","Actors":"Natalie Portman, Hugo Weaving, Stephen Rea, Stephen Fry","Plot":"In a future British tyranny, a shadowy freedom fighter, known only by the alias of \"V\", plots to overthrow it with the help of a young woman.","Language":"English","Country":"USA, UK, Germany","Awards":"5 wins & 20 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BOTI5ODc3NzExNV5BMl5BanBnXkFtZTcwNzYxNzQzMw@@._V1_SX300.jpg","Metascore":"62","imdbRating":"8.2","imdbVotes":"683958","imdbID":"tt0434409","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/40' -d '{"Title":"Kill Bill: Vol. 1","Year":"2003","Rated":"R","Released":"10 Oct 2003","Runtime":"111 min","Genre":"Action","Director":"Quentin Tarantino","Writer":"Quentin Tarantino, Quentin Tarantino (character The Bride), Uma Thurman (character The Bride)","Actors":"Uma Thurman, Lucy Liu, Vivica A. Fox, Daryl Hannah","Plot":"The Bride wakens from a four-year coma. The child she carried in her womb is gone. Now she must wreak vengeance on the team of assassins who betrayed her - a team she was once part of.","Language":"English, Japanese, French","Country":"USA","Awards":"Nominated for 1 Golden Globe. Another 23 wins & 64 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTU1NDg1Mzg4M15BMl5BanBnXkFtZTYwMDExOTc3._V1_SX300.jpg","Metascore":"69","imdbRating":"8.1","imdbVotes":"624119","imdbID":"tt0266697","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/41' -d '{"Title":"Rush","Year":"2013","Rated":"R","Released":"27 Sep 2013","Runtime":"123 min","Genre":"Action, Biography, Drama","Director":"Ron Howard","Writer":"Peter Morgan","Actors":"Chris Hemsworth, Daniel Brühl, Olivia Wilde, Alexandra Maria Lara","Plot":"The merciless 1970s rivalry between Formula One rivals James Hunt and Niki Lauda.","Language":"English, German, Italian, French, Spanish","Country":"UK, Germany, USA","Awards":"Nominated for 2 Golden Globes. Another 8 wins & 50 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQyMDE0MTY0OV5BMl5BanBnXkFtZTcwMjI2OTI0OQ@@._V1_SX300.jpg","Metascore":"75","imdbRating":"8.2","imdbVotes":"246682","imdbID":"tt1979320","Type":"movie","Response":"True"}'
# copy this file to the elasticsearch directory ( ../../elasticsearch-16.0./) and run from there

curl -XPUT 'http://localhost:9200/library/movies/42' -d '{"Title":"Sin City","Year":"2005","Rated":"R","Released":"1 Apr 2005","Runtime":"124 min","Genre":"Crime, Thriller","Director":"Frank Miller, Robert Rodriguez, Quentin Tarantino","Writer":"Frank Miller (graphic novels)","Actors":"Jessica Alba, Devon Aoki, Alexis Bledel, Powers Boothe","Plot":"A film that explores the dark and miserable town, Basin City, and tells the story of three different people, all caught up in violent corruption.","Language":"English","Country":"USA","Awards":"25 wins & 35 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTI2NjUyMDUyMV5BMl5BanBnXkFtZTcwMzU0OTkyMQ@@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.1","imdbVotes":"582130","imdbID":"tt0401792","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/43' -d '{"Title":"Stalker","Year":"1979","Rated":"NOT RATED","Released":"17 Apr 1980","Runtime":"163 min","Genre":"Drama, Sci-Fi","Director":"Andrei Tarkovsky","Writer":"Arkadiy Strugatskiy (novel), Boris Strugatskiy (novel), Arkadiy Strugatskiy (screenplay), Boris Strugatskiy (screenplay)","Actors":"Alisa Freyndlikh, Aleksandr Kaydanovskiy, Anatoliy Solonitsyn, Nikolay Grinko","Plot":"A guide leads two men through an area known as the Zone to find a room that grants wishes.","Language":"Russian","Country":"Soviet Union","Awards":"2 wins & 1 nomination.","Poster":"http://ia.media-imdb.com/images/M/MV5BNDY2NjU0NDAxOF5BMl5BanBnXkFtZTgwNjQ4MTI2MTE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.2","imdbVotes":"57813","imdbID":"tt0079944","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/44' -d '{"Title":"8½","Year":"1963","Rated":"NOT RATED","Released":"25 Jun 1963","Runtime":"138 min","Genre":"Drama","Director":"Federico Fellini","Writer":"Federico Fellini (story), Ennio Flaiano (story), Ennio Flaiano (screenplay), Tullio Pinelli (screenplay), Federico Fellini (screenplay), Brunello Rondi (screenplay)","Actors":"Marcello Mastroianni, Claudia Cardinale, Anouk Aimée, Sandra Milo","Plot":"A harried movie director retreats into his memories and fantasies.","Language":"Italian, English, French, German","Country":"Italy, France","Awards":"Won 2 Oscars. Another 16 wins & 8 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTQ4MTA0NjEzMF5BMl5BanBnXkFtZTgwMDg4NDYxMzE@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.1","imdbVotes":"68750","imdbID":"tt0056801","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/45' -d '{"Title":"The Bourne Ultimatum","Year":"2007","Rated":"PG-13","Released":"3 Aug 2007","Runtime":"115 min","Genre":"Action, Thriller","Director":"Paul Greengrass","Writer":"Tony Gilroy (screenplay), Scott Z. Burns (screenplay), George Nolfi (screenplay), Tony Gilroy (screen story), Robert Ludlum (novel)","Actors":"Matt Damon, Julia Stiles, David Strathairn, Scott Glenn","Plot":"Jason Bourne dodges a ruthless CIA official and his agents from a new assassination program while searching for the origins of his life as a trained killer.","Language":"English, French, Arabic, Russian, Spanish","Country":"USA, Germany","Awards":"Won 3 Oscars. Another 24 wins & 34 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTgzNjMwOTM3N15BMl5BanBnXkFtZTcwMzA5MDY0MQ@@._V1_SX300.jpg","Metascore":"85","imdbRating":"8.1","imdbVotes":"420876","imdbID":"tt0440963","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/46' -d '{"Title":"The Transporter","Year":"2002","Rated":"PG-13","Released":"11 Oct 2002","Runtime":"92 min","Genre":"Action, Crime, Thriller","Director":"Louis Leterrier, Corey Yuen","Writer":"Luc Besson, Robert Mark Kamen","Actors":"Jason Statham, Qi Shu, Matt Schulze, François Berléand","Plot":"Frank is hired to \"transport\" packages for unknown clients and has made a very good living doing so. But when asked to move a package that begins moving, complications arise.","Language":"English, French, Mandarin","Country":"France, USA","Awards":"N/A","Poster":"http://ia.media-imdb.com/images/M/MV5BMTk2NDc2MDAxN15BMl5BanBnXkFtZTYwNDc1NDY2._V1_SX300.jpg","Metascore":"51","imdbRating":"6.8","imdbVotes":"212972","imdbID":"tt0293662","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/47' -d '{"Title":"Jurassic Park","Year":"1993","Rated":"PG-13","Released":"11 Jun 1993","Runtime":"127 min","Genre":"Adventure, Sci-Fi, Thriller","Director":"Steven Spielberg","Writer":"Michael Crichton (novel), Michael Crichton (screenplay), David Koepp (screenplay)","Actors":"Sam Neill, Laura Dern, Jeff Goldblum, Richard Attenborough","Plot":"During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.","Language":"English, Spanish","Country":"USA","Awards":"Won 3 Oscars. Another 24 wins & 16 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg","Metascore":"68","imdbRating":"8.0","imdbVotes":"483680","imdbID":"tt0107290","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/48' -d '{"Title":"The Kings Speech","Year":"2010","Rated":"R","Released":"25 Dec 2010","Runtime":"118 min","Genre":"Biography, Drama, History","Director":"Tom Hooper","Writer":"David Seidler (screenplay)","Actors":"Colin Firth, Helena Bonham Carter, Derek Jacobi, Robert Portal","Plot":"The story of King George VI of the United Kingdom of Great Britain and Northern Ireland, his impromptu ascension to the throne and the speech therapist who helped the unsure monarch become worthy of it.","Language":"English","Country":"UK, USA, Australia","Awards":"Won 4 Oscars. Another 113 wins & 155 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMzU5MjEwMTg2Nl5BMl5BanBnXkFtZTcwNzM3MTYxNA@@._V1_SX300.jpg","Metascore":"88","imdbRating":"8.1","imdbVotes":"418802","imdbID":"tt1504320","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/49' -d '{"Title":"Rocky","Year":"1976","Rated":"PG","Released":"3 Dec 1976","Runtime":"119 min","Genre":"Drama, Sport","Director":"John G. Avildsen","Writer":"Sylvester Stallone","Actors":"Sylvester Stallone, Talia Shire, Burt Young, Carl Weathers","Plot":"Rocky Balboa, a small-time boxer gets a supremely rare chance to fight the heavy-weight champion, Apollo Creed, in a bout in which he strives to go the distance for his self-respect.","Language":"English","Country":"USA","Awards":"Won 3 Oscars. Another 17 wins & 20 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTY5MDMzODUyOF5BMl5BanBnXkFtZTcwMTQ3NTMyNA@@._V1_SX300.jpg","Metascore":"N/A","imdbRating":"8.1","imdbVotes":"306296","imdbID":"tt0075148","Type":"movie","Response":"True"}'

curl -XPUT 'http://localhost:9200/library/movies/50' -d '{"Title":"Prisoners","Year":"2013","Rated":"R","Released":"20 Sep 2013","Runtime":"153 min","Genre":"Crime, Drama, Mystery","Director":"Denis Villeneuve","Writer":"Aaron Guzikowski","Actors":"Hugh Jackman, Jake Gyllenhaal, Viola Davis, Maria Bello","Plot":"When Keller Dovers daughter and her friend go missing, he takes matters into his own hands as the police pursue multiple leads and the pressure mounts. But just how far will this desperate father go to protect his family?","Language":"English","Country":"USA","Awards":"Nominated for 1 Oscar. Another 11 wins & 28 nominations.","Poster":"http://ia.media-imdb.com/images/M/MV5BMTg0NTIzMjQ1NV5BMl5BanBnXkFtZTcwNDc3MzM5OQ@@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.1","imdbVotes":"296282","imdbID":"tt1392214","Type":"movie","Response":"True"}'

